# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4928ac8abf3031564aa700bf5e91a644af56a97cb5be9ac0bdf8f685a8a8065154541e582e5d266a31cf314822ea228f2a030f0a9fc0afc1a491a8b4bea54b4c

test:
  secret_key_base: 9d150e713d1b14043faf8aef043b6bc841a8605feb4c14cea8e96bda287568d9c22e0df66335c715bdd2a477d2ccd740d079efd369094fcfece8237757e15ee3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
